project:
  type: website

website:
  google-analytics: 
    tracking-id: "G-7Z04P679MK"
    storage: "cookies"
    anonymize-ip: true
  cookie-consent: 
   type: implied
   style: simple
   prefs-text: "Wij maken gebruik van cookies om de surfervaring te verbeteren en om de website te optimaliseren. IP-adressen worden niet bewaard."
  title: "Datavisualisatie met ggplot2"
  page-navigation: true
  reader-mode: true
  page-footer:
    right: "Gemaakt met [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Universiteit Antwerpen, 2024"

  sidebar: 
    style: "docked"
    background: "#ADA601"
    foreground: "#FFFFFF"
    pinned: true
    search: true
    align: center
    border: false
    collapse-level: 1
    contents: 
      - text: "Welkom"
        href: index.qmd
      - text: "Introductie van `ggplot2`"
        href: 01_intro.qmd
      - text: "Visualiseren van één numerieke variabele"
        href: 02_numeriek.qmd
      - text: "Visualiseren van één categorische variabele"
        href: 03_categorisch.qmd
      - text: "Meer dan één variabele visualiseren"
        href: 04_meerdere_variabelen.qmd
      - text: "Visualisatie in stijl"
        href: 05_layout.qmd    
tools: 
      - icon: globe
        href: https://www.uantwerpen.be/nl/
        text: "uantwerpen.be/nl/"

lang: nl

format:
  html:
    theme: [flatly, theme.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    
